<?php

global $listCmdYamahaRemoteControl;

$listCmdYamahaRemoteControl = [
	[
		'name' => 'Etat AVR',
		'logicalId' => 'power',
		'type' => 'info',
		'subType' => 'binary',
		'order' => 1,
		'isVisible' => 1,
		'configuration' => [
			'tab_name' => 'tab_touche',
			'path' => 'System,Power_Control,Power',
			'value' => 0,
		],
		'generic_type' => 'GENERIC_STATE',
	],
	[
		'name' => 'Entrée',
		'logicalId' => 'input',
		'type' => 'info',
		'subType' => 'string',
		'order' => 2,
		'isVisible' => 1,
		'configuration' => [
			'tab_name' => 'tab_touche',
			'path' => 'Main_Zone,Input,Input_Sel_Item',
			'value' => '',
		],
		'generic_type' => 'GENERIC_STATE',
	],
	[
		'name' => 'Volume',
		'logicalId' => 'volume',
		'type' => 'info',
		'subType' => 'numeric',
		'unite' => 'dB',
		'order' => 3,
		'isVisible' => 1,
		'configuration' => [
			'tab_name' => 'tab_touche',
			'path' => 'Main_Zone,Volume,Lvl',
			'param' => 'Val',
			'value' => 0,
		],
		'generic_type' => 'GENERIC_STATE',
	],
	[
		'name' => 'Mute_info',
		'logicalId' => 'mute',
		'type' => 'info',
		'subType' => 'binary',
		'order' => 4,
		'isVisible' => 0,
		'configuration' => [
			'tab_name' => 'tab_touche',
			'value' => 0,
		],
		'generic_type' => 'GENERIC_STATE',
	],
	[
		'name' => 'ON-OFF',
		'logicalId' => 'touche',
		'type' => 'action',
		'subType' => 'other',
		'order' => 5,
		'isVisible' => 1,
		'configuration' => [
			'tab_name' => 'tab_touche',
			'code_touche'=> 'System,Power_Control,Power',
		],
		'generic_type' => 'GENERIC_ACTION',
		'forceReturnLineAfter' => '1',
	],
	[
		'name' => 'VOL+',
		'logicalId' => 'touche',
		'type' => 'action',
		'subType' => 'other',
		'order' => 6,
		'isVisible' => 1,
		'configuration' => [
			'tab_name' => 'tab_touche',
			'code_touche'=> 'Main_Zone,Volume,Lvl',
			'value' => '<Val>Up</Val><Exp></Exp><Unit></Unit>',
		],
		'generic_type' => 'GENERIC_ACTION',
		'forceReturnLineAfter' => '0',
	],
	[
		'name' => 'VOL-',
		'logicalId' => 'touche',
		'type' => 'action',
		'subType' => 'other',
		'order' => 7,
		'isVisible' => 1,
		'configuration' => [
			'tab_name' => 'tab_touche',
			'code_touche'=> 'Main_Zone,Volume,Lvl',
			'value' => '<Val>Down</Val><Exp></Exp><Unit></Unit>',
		],
		'generic_type' => 'GENERIC_ACTION',
		'forceReturnLineAfter' => '0',
	],
	[
		'name' => 'MUTE',
		'logicalId' => 'touche',
		'type' => 'action',
		'subType' => 'other',
		'order' => 8,
		'isVisible' => 1,
		'configuration' => [
			'tab_name' => 'tab_touche',
			'code_touche'=> 'Main_Zone,Volume,Mute',
		],
		'generic_type' => 'GENERIC_ACTION',
		'forceReturnLineAfter' => '1',
	],
];